spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-prod
    username: postgres
    password: postgres1
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect