DROP TABLE IF EXISTS sensors;


CREATE TABLE IF NOT EXISTS sensors (
    id SERIAL PRIMARY KEY,
    device_id text NOT NULL,
    Month INTEGER NOT NULL,
    Year INTEGER NOT NULL,
    pH REAL NOT NULL,
    Ba REAL NOT NULL,
    Cu REAL NOT NULL,
    Fe REAL NOT NULL,
    Viruses REAL NOT NULL
);


